### ISSUE TITLE
Feature request: Resource coloring

### ISSUE THREAD

**Issue by Raijinili** [Grae-Drake/hg-units#23]
Have some kind of visual indicator for a card's resource.

Simple: Pyeontae's Matrix had a colored bar at the top of each card that was yellow, blue, green, or black (hybrid), depending on the resource to buy that unit.

More complex: if a unit costs both Gold and Crystal, make the bar half yellow and half blue.

Even more complex: If a unit costs 5 Gold and 3 Crystal, make it 5/8 yellow and 3/8 blue.

**Comment by Grae-Drake** [comment]
I'd like to start by adding resource icons from Scott's sprite sheet.  Interested in taking a crack at that?

**Comment by Raijinili** [comment]
Uuuuuh...

Can't we make Xyn do it?

**Comment by Grae-Drake** [comment]
Probably not?  I don't think CSS is up his alley, though I could be wrong.  Does tagging @xyntech work?

Take a look hur: https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/CSS_Image_Sprites

Pretty simple, just don't want to deal with it atm.

**Comment by Grae-Drake** [comment]
Complete & closed.
