### ISSUE TITLE
[Feature] Store collections/decks on client side

### ISSUE THREAD

**Issue by Raijinili** [Grae-Drake/hg-units#25]
So there are two basic options for this:
1. Cookies.
2. HTML5 Client-Side Storage.

Cookies have limits (and can be overwritten without warning when there are too many), and client-side storage is a new feature (and thus not always implemented; my up-to-date Firefox doesn't seem to have it natively).

Edit: I think I got confused about local storage. Seems that even IE6 has HTML5 storage, and with a high enough limit for this project.

**Comment by Grae-Drake** [comment]
Complete with 5546c80ee6534b8ba532c9de183f904f5a713651!
